[package]
name = "bdaylog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
regex = "1.10.5"
rusqlite = { version = "0.31.0", features = ["bundled"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
